function createfigure(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 15-Jun-2019 14:56:34

% Create figure
figure;



y=0.5 + 2*x - cos(12*x -9);

plot(x,y)

axis([0 31 -5 40])
set(gca,'FontSize',15)
